apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab8-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/abdenourbarache/lab6.git'
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lab8-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
